#!/bin/bash

source src/functions;

DATABASE=$(cat src/database);

echo "Checando status do postgres..." &&
checkPostgres &&

echo "Destruindo banco de dados..." &&
destroyDatabase $DATABASE;

DATABASE=$(cat src/database_test);

echo "Checando status do postgres..." &&
checkPostgres &&

echo "Destruindo banco de dados..." &&
destroyDatabase $DATABASE;
